spring:
  datasource:
    url: jdbc:mysql://localhost:3306/talent?serverTimezone=UTC&useUnicode=true&characterEncoding=utf-8
    username: root
    password: lsm010102
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    show-sql: true
server:
  address: 0.0.0.0
  port: 8088

